### PR TITLE
yb-ctl should allow flags at end of command

### PR DESCRIPTION
**Pull request by WesleyW**
We currently have an odd state where flags for `yb-ctl` can only appear at odd places (e.g. `yb-ctl --rf 3 create --v`). This PR makes it so `yb-ctl` will accept flags at the end of the command (`yb-ctl create --rf 3 --v`). At a later passthrough, we should require `yb-ctl` to only accept flags at the end ([yugabyte/yugabyte-db#2440](https://github.com/yugabyte/yugabyte-db/issues/2440)).

### CODE REVIEW

**Comment by jaki** [comment]
You may want @mbautin to take a look at this as well.  One reason against this change is that it seems that the parent and sub parsers share the same flags, so you have to be extra careful to not have conflicts between them (e.g. `--v` and `--verbose` is a close call).  However, this change can be good if we ever get to a point of supporting issue yugabyte/yugabyte-db#1070, where flags can appear anywhere, not just the end.

**Comment by mbautin** [comment]
The way I look at it is that for any global flags (flags affecting all commands), they could be accepted before or after the command, but it is OK to only accept command-specific flags at the end of a command.

**Comment by mbautin** [comment]
LGTM.

**Comment by WesleyW** [comment]
@mbautin @jj-kim This is actually to fix  [yugabyte/yugabyte-db#1070](https://github.com/yugabyte/yugabyte-db/issues/1070). While we're in the process of updating our docs, we'llsupport having the flag both before and after. Will need another pass later to remove that support because of [yugabyte/yugabyte-db#2440](https://github.com/yugabyte/yugabyte-db/issues/2440). Updated the title/body to reflect that.

**Pull request merged**
